Fix requires in extension.json
It must be MediaWiki/skins/extenions on the first level, than the
extension can be listed

PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with
message 'Dependency type PluggableAuth unknown in OpenID Connect' in
/srv/jenkins-workspace/workspace/mwext-testextension-php55/src/includes/registration/VersionChecker.php:126
Stack trace:
#0
/srv/jenkins-workspace/workspace/mwext-testextension-php55/src/includes/registration/ExtensionRegistry.php(246):
VersionChecker->checkArray(Array)
#1
/srv/jenkins-workspace/workspace/mwext-testextension-php55/src/includes/registration/ExtensionRegistry.php(148):
ExtensionRegistry->readFromQueue(Array)
#2
/srv/jenkins-workspace/workspace/mwext-testextension-php55/src/includes/Setup.php(40):
ExtensionRegistry->loadFromQueue()
#3
/srv/jenkins-workspace/workspace/mwext-testextension-php55/src/maintenance/doMaintenance.php(98):
require_once('/srv/jenkins-wo...')
#4
/srv/jenkins-workspace/workspace/mwext-testextension-php55/src/maintenance/update.php(217):
require_once('/srv/jenkins-wo...')
#5 {main}
  thrown in
/srv/jenkins-workspace/workspace/mwext-testextension-php55/src/includes/registration/VersionChecker.php
on line 126

Fatal error: Uncaught exception 'UnexpectedValueException' with message
'Dependency type PluggableAuth unknown in OpenID Connect' in
/srv/jenkins-workspace/workspace/mwext-testextension-php55/src/includes/registration/VersionChecker.php
on line 126

Change-Id: If7d14b1f1a37427222a85a0a4f61beae751af947